ARG ADMIN_UI_VERSION=0.5.1

FROM alpine:3.18 AS builder
ARG ADMIN_UI_VERSION
WORKDIR /release
ADD https://github.com/socketio/socket.io-admin-ui/archive/refs/tags/$ADMIN_UI_VERSION.tar.gz ./release.tar.gz 
RUN tar -xvf release.tar.gz --strip 1

FROM nginx:1.25.2-alpine3.18
COPY --from=builder /release/ui/dist /usr/share/nginx/html/ui