kind: pipeline
type: docker
name: build and deploy
steps:
- name: build
  image: node:18.16.0-alpine
  commands:
  - npm ci
  - npm run package
- name: create release
  image: plugins/gitea-release
  settings:
    api_key: 
        from_secret: API_KEY
    base_url:
        from_secret: URL
    files: dist/*