---
kind: pipeline
name: generate-docs

steps:
  - name: generate docs
    image: python:3
    commands:
      - pip install json-schema-for-humans
      - mkdir -p out/docs
      - generate-schema-doc src/schema/config.schema.json out/docs/schema.html
  - name: deploy
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME:
        from_secret: ftp_username
      FTP_PASSWORD:
        from_secret: ftp_password
      PLUGIN_HOSTNAME: ftp.jwetzell.com:21
      PLUGIN_SRC_DIR: /out/docs
      PLUGIN_DEST_DIR: /docs
      PLUGIN_SECURE: true
      PLUGIN_VERIFY: false
      PLUGIN_CLEAN_DIR: true
