---
kind: pipeline
type: exec
name: package

platform:
  os: linux
  arch: amd64

steps:
  - name: package
    commands:
      - nvm install
      - nvm use
      - npm ci
      - npm package
      - ls dist
