---
kind: pipeline
name: generate-schema-docs
trigger:
  branch:
    - master
steps:
  - name: generate schema docs
    image: python:3
    commands:
      - pip install json-schema-for-humans
      - mkdir -p html/docs/schema/config
      - generate-schema-doc --config link_to_reused_ref=false --config expand_buttons=true src/schema/config.schema.json html/docs/schema/config/index.html
  - name: deploy schema docs
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME:
        from_secret: ftp_username
      FTP_PASSWORD:
        from_secret: ftp_password
      PLUGIN_HOSTNAME: ftp.jwetzell.com:21
      PLUGIN_SRC_DIR: /html/docs/schema/config
      PLUGIN_DEST_DIR: /docs/schema/config
      PLUGIN_SECURE: true
      PLUGIN_VERIFY: false
      PLUGIN_CLEAN_DIR: true
---
kind: pipeline
name: NPM publish
trigger:
  event:
    - tag
steps:
  - name: install_and_package
    image: node:18.16.1-alpine
    commands:
      - npm version ${DRONE_TAG}
      - npm ci
      - npm run package
  - name: release
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_api_key
      base_url: https://git.jwetzell.com
      files: dist/bin/*
      draft: true
    depends_on:
      - install_and_package
  - name: npm publish
    image: plugins/npm
    settings:
      token:
        from_secret: npm_token
    depends_on:
      - release
