---
kind: pipeline
name: generate-schema-docs
trigger:
  branch:
    - main
  event:
    - push
steps:
  - name: generate schema docs
    image: python:3
    commands:
      - pip install json-schema-for-humans
      - mkdir -p html/docs/schema/config
      - generate-schema-doc --config expand_buttons=true schema/config.schema.json html/docs/schema/config/index.html
  - name: deploy schema docs
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME:
        from_secret: ftp_username
      FTP_PASSWORD:
        from_secret: ftp_password
      PLUGIN_HOSTNAME:
        from_secret: ftp_hostname
      PLUGIN_SRC_DIR: /html/docs/schema/config
      PLUGIN_DEST_DIR: /docs/schema/config
      PLUGIN_SECURE: true
      PLUGIN_VERIFY: false
      PLUGIN_CLEAN_DIR: true
---
kind: pipeline
name: NPM Publish
trigger:
  event:
    - tag
steps:
  - name: set version
    image: node:18.16.1-alpine
    commands:
      - npm version ${DRONE_TAG}
  - name: npm publish
    image: plugins/npm
    settings:
      token:
        from_secret: npm_token
