name: Publish lib docs to docs site
on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./lib

      - run: npm run docs
        working-directory: ./lib

      - name: publish docs
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FTP_URL}}
          username: ${{secrets.DOCS_FTP_USERNAME}}
          password: ${{secrets.DOCS_FTP_PASSWORD}}
          local-dir: ./lib/dist/docs/
          server-dir: lib/
          port: 21
          protocol: ftps
