name: Publish webui to demo site
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'webui/**'
      - 'schema/**'
      - 'sample/config/default.json'
jobs:
  build-webui:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'webui/package-lock.json'

      - name: install Node.js dependencies
        run: npm ci
        working-directory: ./webui

      - name: build demo site
        run: npm run build:demo
        working-directory: ./webui

      - name: copy default config
        run: cp sample/config/default.json ./webui/dist/webui/browser/config.json

      - name: copy schema
        run: cp schema/config.schema.json ./webui/dist/webui/browser/config.schema.json

      - name: Publish demo webui
        uses: SamKirkland/FTP-Deploy-Action@8e83cea8672e3fbcbb9fdafff34debf6ae4c5f65 # v4.3.5
        with:
          server: ${{secrets.FTP_URL}}
          username: ${{secrets.DEMO_FTP_USERNAME}}
          password: ${{secrets.DEMO_FTP_PASSWORD}}
          local-dir: ./webui/dist/webui/browser/
          server-dir: /
          port: 21
          protocol: ftps
