name: Publish @showbridge/cli to builds site
on:
  workflow_dispatch:
  push:
    tags:
      - 'cli/**'
jobs:
  publish-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: 'cli/package-lock.json'

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./cli

      - name: extract version
        id: extract-version
        run: node -e "console.log('cli-version='+require('./package.json').version)" >> $GITHUB_OUTPUT
        working-directory: ./cli

      - name: pack
        run: npm pack
        working-directory: ./cli

      - name: publish to ftp
        uses: SamKirkland/FTP-Deploy-Action@8e83cea8672e3fbcbb9fdafff34debf6ae4c5f65 # v4.3.5
        with:
          server: ${{secrets.FTP_URL}}
          username: ${{secrets.BUILDS_FTP_USERNAME}}
          password: ${{secrets.BUILDS_FTP_PASSWORD}}
          local-dir: ./cli/
          server-dir: cli/${{steps.extract-version.outputs.cli-version}}/
          port: 21
          protocol: ftps
          exclude: |
            **/*
            !*.tgz
