name: Publish @showbridge/types to builds site
on:
  workflow_dispatch:
  push:
    tags:
      - 'types/**'
jobs:
  publish-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: 'types/package-lock.json'

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./types

      - name: extract version
        id: extract-version
        run: node -e "console.log('types-version='+require('./package.json').version)" >> $GITHUB_OUTPUT
        working-directory: ./types

      - name: pack
        run: npm pack
        working-directory: ./types

      - name: publish to ftp
        uses: SamKirkland/FTP-Deploy-Action@8e83cea8672e3fbcbb9fdafff34debf6ae4c5f65 # v4.3.5
        with:
          server: ${{secrets.FTP_URL}}
          username: ${{secrets.BUILDS_FTP_USERNAME}}
          password: ${{secrets.BUILDS_FTP_PASSWORD}}
          local-dir: ./types/
          server-dir: types/${{steps.extract-version.outputs.types-version}}/
          port: 21
          protocol: ftps
          exclude: |
            **/*
            !*.tgz
