name: Publish webui to demo site
on:
  push:
    branches:
      - main
    paths:
      - 'webui/**'
      - 'schema/**'
      - 'sample/config/default.json'
jobs:
  build-webui:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4

      - name: set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install Node.js dependencies
        run: npm ci
        working-directory: ./webui

      - name: build demo site
        run: npm run build:demo
        working-directory: ./webui

      - name: copy default config
        run: cp sample/config/default.json ./webui/dist/webui/config.json

      - name: copy schema
        run: cp schema/config.schema.json ./webui/dist/webui/config.schema.json

      - name: Publish demo webui
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FTP_URL}}
          username: ${{secrets.DEMO_FTP_USERNAME}}
          password: ${{secrets.DEMO_FTP_PASSWORD}}
          local-dir: ./webui/dist/webui/
          server-dir: /
          port: 21
          protocol: ftps
