name: Publish @showbridge/docs to builds site
on:
  workflow_dispatch:
  push:
    tags:
      - 'docs/**'
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: 'docs/package-lock.json'

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./docs

      - name: extract version
        id: extract-version
        run: node -e "console.log('docs-version='+require('./package.json').version)" >> $GITHUB_OUTPUT
        working-directory: ./docs

      - name: build
        run: npm run build
        working-directory: ./docs

      - name: pack
        run: npm pack
        working-directory: ./docs

      - name: publish to ftp
        uses: SamKirkland/FTP-Deploy-Action@8e83cea8672e3fbcbb9fdafff34debf6ae4c5f65 # v4.3.5
        with:
          server: ${{secrets.FTP_URL}}
          username: ${{secrets.BUILDS_FTP_USERNAME}}
          password: ${{secrets.BUILDS_FTP_PASSWORD}}
          local-dir: ./docs/
          server-dir: docs/${{steps.extract-version.outputs.docs-version}}/
          port: 21
          protocol: ftps
          exclude: |
            **/*
            !*.tgz
