name: Publish cloud docker image
on:
  push:
    branches:
      - 'main'
    paths:
      - 'cloud/**'
    tags:
      - 'cloud/v*'
jobs:
  build-cloud-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            jwetzell/showbridge-cloud
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./cloud/
          file: ./cloud/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
