name: publish-cloud-main
on:
  push:
    branches:
      - 'main'
    paths:
      - 'cloud/**'
jobs:
  build-cloud-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./cloud/
          file: ./cloud/Dockerfile
          tags: jwetzell/showbridge-cloud:main